### ISSUE TITLE
running tests causes "Fatal Python Error"

### ISSUE THREAD

**Issue by keatonb** [lightkurve/lightkurve#1071]
Following the instructions at http://docs.lightkurve.org/about/testing.html?highlight=tests#how-do-i-run-tests-locally

When I try to run tests (or run any Python) from within the `tests` directory, I get:
> Fatal Python error: init_sys_streams: can't initialize sys standard streams
> AttributeError: module 'io' has no attribute 'OpenWrapper'

This is caused by the new addition of a subdirectory called `io` that Python finds deeply troubling.

Renaming `tests/io` to anything else solves this problem.

**Comment by barentsen** [comment]
Thanks for raising this issue @keatonb!

The key solution to this problem is to execute `pytest tests/` (or `poetry run pytest tests/`) from the root of the repository. 

Renaming `tests/io` would resolve the specific error you encountered, but there could be other (undetected?) conflicts between local Python files and package imports.  For this reason, we should always avoid running tests from inside a directory that contains Python files.

The instructions you followed ignored this best practice and need to be updated. Apologies!  I'll leave this issue open until the docs are updated!
