### ISSUE TITLE
[Question] How to retrieve Kepler/K2 TPFs with more than default pixels?

### ISSUE THREAD

**Issue by martindevora** [lightkurve/lightkurve#1074]
#### Problem description

Is there any way to retrieve a TPF with a different number of pixels than the default ones?

#### Example

```python
import lightkurve
lightkurve.search_targetpixelfile("KIC 12557548", mission="Kepler", cadence=60, quarter=13).download_all()
```

#### Expected behavior

The example returns 6x6 px images. Is there any way to get, for instance, 22x22 px images? I tried to use the `cutout_size` parameter but I read that it is only intended for TESS FFIs and of course, doesn't work for Kepler. I also haven't been able to find anything regarding this in the tutorials.

#### Environment
-  platform (e.g. Linux, OSX, Windows): Ubuntu 18
-  lightkurve version (e.g. 1.0b6): 2.0.2
-  installation method (e.g. pip, conda, source): python3.8 -m pip

**Comment by barentsen** [comment]
@martindevora Excellent question!

Due to storage and downlink limitations, Kepler only recorded pre-defined pixel regions around targets.  All those pixels are made available in the Target Pixel Files.

In the case of your example, 22x22 pixels were never sent back to Earth, only 6x6 pixels are available.

Kepler did take a full-frame FFI image about once a month (2-3 per quarter), so you can dig out a single 22x22 pixel image from there, but there is no easy "KeplerCut" service for this because the number of FFIs is so small.

As you mention, TESS does take FFIs every 10-30 minutes, and unlike Kepler, every single pixel is sent back to Earth, which is why we love TESS!

**Comment by martindevora** [comment]
> @martindevora Excellent question!
> 
> Due to storage and downlink limitations, Kepler only recorded pre-defined pixel regions around targets. All those pixels are made available in the Target Pixel Files.

This I knew, but I expected some more pixels around each target for some reason.
> 
> In the case of your example, 22x22 pixels were never sent back to Earth, only 6x6 pixels are available. If any extra pixels were downloaded, you should be able to find another Target Pixel File for them in the archive. You can try passing the parameter `radius=120` to `search_targetpixelfile()` to check whether another target is present within 120 arcseconds, but that's quite unlikely.
> 
> Kepler did send back a full-frame FFI image about once a month (2-3 per quarter), so you can dig out a single 22x22 pixel image from there, but there is no easy "KeplerCut" service for this because the number of FFIs is so small.
> 
I guess there's little to do here I'm afraid. Thanks for the info.

> As you mention, TESS does take FFIs every 10-30 minutes, and unlike Kepler, every single pixel is sent back to Earth, which is why we love TESS!

**Comment by barentsen** [comment]
> I expected some more pixels around each target for some reason.

The exact number of pixels selected depended on the brightness of the target (bright targets got more pixels) and the amount of spacecraft motion predicted for a given location on the spacecraft (e.g. K2 targets received more pixels), so you may have encountered TPFs before that were much larger than 6x6!

**Comment by barentsen** [comment]
Closing this issue.  Feel free to reopen should there be any follow-up questions! :+1:
