### ISSUE TITLE
Contributing guidelines 404

### ISSUE THREAD

**Issue by benjaminpope** [lightkurve/lightkurve#1285]
#### Problem description
I'm getting a 404 on opening the contributing guidelines at  https://docs.lightkurve.org/about/contributing.html.

**Comment by christinahedges** [comment]
Hi @benjaminpope, thanks for bringing this up! I reorganized the website very slightly to split the docs into *[About](http://docs.lightkurve.org/about/index.html)* and *[Developing](http://docs.lightkurve.org/development/index.html)* tabs so that folks who aren't interested in developing don't get inundated with new information. The contributing page is here:
http://docs.lightkurve.org/development/contributing.html

Does that answer your issue?

**Comment by benjaminpope** [comment]
Yes!
