### ISSUE TITLE
Is it possible to analyse lightcurves from OGLE using lightkurve? 

### ISSUE THREAD

**Issue by Anohita1** [lightkurve/lightkurve#1352]
#### Problem description
They are available as .dat files with 5 columns - I band and V band magnitudes , corresponding errors and HJD. The magnitudes can of course be converted to fluxes. I want to calculate global seismic parameters using some of these lightcurves which span over 2 years. I had few questions- 
1. like the default TESS and Kepler lightcurves have fluxes in electrons/s is it necessary to convert these fluxes in the same units? If so, what is the zero-point flux conversion value for OGLE in electrons/s?
2. For time-axis, is HJD alright? Or a conversion to MJD or BJD is required?

#### Environment

-  platform (Linux):
-  lightkurve version (2.4.0):
-  installation method (pip):

**Comment by tylerapritchard** [comment]
Hi Anohita1 - thanks for reaching out! Lightkurve development is currently designed for TESS and Kepler datasets, due to their somewhat unique data properties and to enable the Lightkurve project to maintain a supportable & sustainable scope. 

That said, using non TESS & Kepler data is possible, though not actively supported by us and not necessarily robust across all lightkurve features. Doing this would require you to be comfortable delving into the weeds of the code a bit and seeing if what you need is possible. 

You can construct a generic lightkurve class which requires time, flux, and flux_err from OGLE inputs that you create, and explore from there, e.g.: 

`import lightkurve as lk
lc = lk.LightCurve(data={'time': time_array, 'flux': flux_array, 'other_column': some_other_array})`
There’s some discussion on issue  #1129 as well that might help if you choose to pursue this.

Regarding your technical questions- you probably will want the flux column to be in a unit of flux to make sure that it is consistent with Kepler and TESS units and minimize potential issues (which will depend on what you're doing).  I’m not familiar with the OGLE telescope details and how it pertains to your analysis, the flux conversions may depend on your source & goals, etc. For the lightkurve time axis - any version of JD / days/ etc should work fine as long as it is consistent across all data-points. 

Best of luck with your analysis!
