### ISSUE TITLE
`df_sso=lc.query_solar_system_objects(cadence_mask='all')` Query Fail

### ISSUE THREAD

**Issue by RandomNewz** [lightkurve/lightkurve#1396]
#### Problem description
`df_sso=lc.query_solar_system_objects(cadence_mask='all')` OSError: SkyBot Solar System Query Failed, with TIC 180672438, Sector 49, and using SPOC

#### Example

```python
df_sso=masked_lc.query_solar_system_objects(cadence_mask='all')
# insert code here ...
```
(Up: Code)
(Down: Error)

```python
OSError: SkyBot Solar System query failed.
URL used:
http://vo.imcce.fr/webservices/skybot/skybotconesearch_query.php?-mime=text&-ra=200.484722254323&-dec=40.2684038857193&-bd=0.0875&-loc=C57&EPOCH=2459640.7268652557
Response received:
# Flag: -1
# Ticket: 178729097680769834
SkyBoT asteroid conesearch -> numIntAstromJ2000_para[1]: computeEphemeris: 
#Error
```
#### Expected behavior
Supposed to give out a list of all SSO's that have impacted the curve.

#### Environment

-  platform: Windows
-  lightkurve version: 2.4.2
-  installation method: pip

**Comment by orionlee** [comment]
There seems to some issue in the underlying Skybot service. I started experience it in late December 2023. E.g., if I use Skybot's web UI:
  https://vo.imcce.fr/webservices/skybot/?forms

I cannot get any meaningful results either.

**Comment by RandomNewz** [comment]
So, nothing can be done until the Skybot service gets fixed?

**Comment by orionlee** [comment]
If the goal is to identify specific asteroids around the target of the lightcurve, I'm afraid I don't have any suggestion.

If the goal is to see if there are asteroids (or any type of background events) that contaminate a lightcurve, there are ways without using Skybot (identifying specific asteroids).

1. one can inspect the background, in `SAP_BKG` for TESS SPOC lightcurves, to identify dips in lightcurves due to spikes in the background (often due to asteroids passing through).

```python
lc = lc.truncate(3256.1, 3256.4)  # zoom-in to the relevant time
lc.scatter();
lc.select_flux("sap_bkg").scatter(label="sap_bkg");
```
![image](https://github.com/lightkurve/lightkurve/assets/250644/80e30c57-8783-4e8c-ad17-708877338502)

2. If `TargetPixelFile` is available, one can inspect the lightcurve at per-pixel level with  [tpf.plot_pixels()](https://docs.lightkurve.org/reference/api/lightkurve.KeplerTargetPixelFile.plot_pixels.html#lightkurve.KeplerTargetPixelFile.plot_pixels) function. The trajectory of an asteroid can often be seen visually:

![image](https://github.com/lightkurve/lightkurve/assets/250644/231b57aa-9594-4592-be1a-f69626f9830f)

**Comment by orionlee** [comment]
@RandomNewz Skybot service is functioning again. So the issue is resolved.
