### ISSUE TITLE
`periodogram` missing from `__init__` file

### ISSUE THREAD

**Issue by soichiro-hattori** [lightkurve/lightkurve#1413]
#### Problem description

The `periodogram` module is not imported in the `__init__.py` file, making it a bit cumbersome to access directly.
This issue would be resolved by adding
```python
from .periodogram import *
```
to the `__init__.py` file.

#### Example

```python
import lightkurve
lightkurve.periodogram
```
```python
AttributeError: module 'lightkurve' has no attribute 'periodogram'
```

#### Expected behavior

To be able to use `lightkurve.periodogram.LombScarglePeriodogram(*)` or `lightkurve.periodogram.BoxLeastSquaresPeriodogram(*)` to directly access the classes the same way it is possible for other objects. 

#### Environment

-  platform (e.g. Linux, OSX, Windows): macOS
-  lightkurve version (e.g. 1.0b6): 2.5.0dev
-  installation method (e.g. pip, conda, source): source

**Comment by Nschanche** [comment]
Hi @soichiro-hattori, thank you for opening this issue! Lightkurve has basically wrapped the astropy BLS/Lomb Scargle periodogram functions so that you can directly call the periodogram function on a lightcurve object (pgrm = lc.to_periodogram() returns a periodogram object). The wrapper is therefore specific to the way the lightcurve object is set up in the lightkurve package. If you want to create a periodogram given generic time series data, it may be better to import and use the astropy implementation directly. So, I'm not sure if we really want the periodgram exposed directly. Thoughts @christinahedges or @tylerapritchard ?

**Comment by soichiro-hattori** [comment]
Thank you for the response @Nschanche! I thought that might be the reason!
Happy to close this issue if it's better to not expose it.

**Comment by tylerapritchard** [comment]
Hey @soichiro-hattori, thanks for reaching out!! Do you have a particular use case where this would be beneficial to you?  

I think that basically I agree with @Nschanche here, but I do see what you're saying. This would be more consistent across subpackages, and is not a huge change. 

However, our periodogram constructors all basically require a lightcurve object (and are wrapped by lightcurve.to_periodogram), so it is not clear to me that there would be a significant workflow benefit here.

**Comment by Nschanche** [comment]
It sounds like we want to keep this as-is at the moment. I'm closing this issue for now, but please open it back up if a strong use-case where this may be useful presents itself.
