### ISSUE TITLE
Inconsistent amplitudes in stitched light curves

### ISSUE THREAD

**Issue by panjiashu** [lightkurve/lightkurve#1420]
#### Problem description
This is a data problem rather than a software problem. I downloaded all Kepler long cadence data of KIC 9845323 and stitched them, but found that the amplitudes of some quarters, e.g. Q7 (810-900 BKJD day) are significantly smaller than those of other quarters. I've looked up the asteroseismic logg of KIC 9845323 to be 1.6, which corresponds to the larger amplitudes in the plot. What could be the reason for the significantly compressed amplitudes of those quarters like Q7? Any advice would be appreciated.

#### Example

```python
import lightkurve as lk
search_result = lk.search_lightcurve('KIC 9845323',
                    cadence='long',
                    author='Kepler',)
lc = search_result.download_all().stitch()
lc.plot()
```
![stitch_err](https://github.com/lightkurve/lightkurve/assets/63895067/bff0281e-209a-4488-b23c-854ddd409f35)

#### Expected behavior
I expect the stitch function would give me a stitched light curve with consistent amplitudes across quarters.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Linux
-  lightkurve version (e.g. 1.0b6): 2.4.2
-  installation method (e.g. pip, conda, source): pip

**Comment by Nschanche** [comment]
Hi @panjiashu, the stitch function by default will normalize each individual lightcurve in the collection, so each sector is normalized separately. I looked at each sector separately and can see there are a few issues. 
```for ii in range(len(search_result)):
    search_result[ii].download().plot()```
This target is bright and near the saturation limit for Kepler. In sector 1 for example, you can see there are some unusual jumps in the lightcurve. If you download the target pixel file and plot it with the pipeline aperture, you can see that the pipeline is only the two 2 brightest pixels. 
<img width="751" alt="Screenshot 2024-05-01 at 2 36 12 PM" src="https://github.com/lightkurve/lightkurve/assets/8659773/59be1ebf-f5bd-4da4-ab72-d16da5b28686">

When these pixels saturate, the aperture mask does not capture the flux that bleeds to the surrounding pixels, leading to the strange behavior. I would recommend you remake the light curves using a larger aperture so that the total flux is captured. You can check out [this tutorial](https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-custom-aperture-photometry.html) if you are unfamiliar with that process.

**Comment by panjiashu** [comment]
> Hi @panjiashu, the stitch function by default will normalize each individual lightcurve in the collection, so each sector is normalized separately. I looked at each sector separately and can see there are a few issues.
> 
> ```
> for ii in range(len(search_result)):
>     search_result[ii].download().plot()
> ```
> 
> This target is bright and near the saturation limit for Kepler. In sector 1 for example, you can see there are some unusual jumps in the lightcurve. If you download the target pixel file and plot it with the pipeline aperture, you can see that the pipeline is only the two 2 brightest pixels. <img alt="Screenshot 2024-05-01 at 2 36 12 PM" width="751" src="https://private-user-images.githubusercontent.com/8659773/327204923-59be1ebf-f5bd-4da4-ab72-d16da5b28686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTYyNzksIm5iZiI6MTcxNDYxNTk3OSwicGF0aCI6Ii84NjU5NzczLzMyNzIwNDkyMy01OWJlMWViZi1mNWJkLTRkYTQtYWI3Mi1kMTZkYTViMjg2ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMDIxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDIwMzUwMTY3MDk4ZTZmN2U0YjIyMDMwYzVjNzRmMmI3MDIyYzZmZWM1YmNlY2IyOTM1MTRmZTEyMzk5MTNlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ehg13p5f2fkNwKFJQ7vV-ghnR4-ce6_Q3EcXM7Helbc">
> 
> When these pixels saturate, the aperture mask does not capture the flux that bleeds to the surrounding pixels, leading to the strange behavior. I would recommend you remake the light curves using a larger aperture so that the total flux is captured. You can check out [this tutorial](https://docs.lightkurve.org/tutorials/2-creating-light-curves/2-1-custom-aperture-photometry.html) if you are unfamiliar with that process.

This clears my problem. Many thanks!
