### ISSUE TITLE
Interact_BLS needs a tutorial

### ISSUE THREAD

**Issue by christinahedges** [lightkurve/lightkurve#729]
It's a bit of a hidden feature

**Comment by orionlee** [comment]
I took a stab:
  https://gist.github.com/orionlee/72c5f3988f336e2d6c395311dd4feb45

It is roughly based on :
https://github.com/barentsen/kepler-athenaeum-tutorial/blob/master/how-to-find-a-planet-tutorial.ipynb

using Lightkurve / `interact_bls()`

So far it is disjoint from the [periodogram tutorial](https://docs.lightkurve.org/tutorials/01-using-the-periodogram-class.html). The two should probably be combined or tweaked, so that they reference one another.

If something like it is deemed helpful, I can get it into a PR.

**Comment by rebekah9969** [comment]
There is now an interact_bls() section within the [Interactively inspecting Target Pixel Files](https://docs.lightkurve.org/tutorials/1-getting-started/interactively-inspecting-data.html?highlight=interact_bls) tutorial. 

I think that this can now be closed.

**Comment by Nschanche** [comment]
There is now a small tutorial with interact_bls in the "Interactively inspecting Target Pixel Files" tutorial. However, it looks like the visuals are slightly outdated. The current lightkurve shows the phase folded lightkurve in JD units, while the tutorial shows normalized phase. Leaving this open in case we want to update or expand the interact_bls tutorial section.
