### ISSUE TITLE
2.0 upgrade compatibility- LightCurve.fold() 's phase is no longer normalized by default.

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#853]
#### Problem description

The result of `fold()` does not seem to be correct. See the example below.

#### Example

```python
from lightkurve.search import search_lightcurve
lc = search_lightcurve('KIC 10264202', quarter=10).download(download_dir='data').PDCSAP_FLUX.normalize()
lc_fold = lc.fold(0.517, 907.37624)
lc_fold.scatter()
```

The phase of the folded LC with Lightkurve2 isn't quite right (only from -0.25 to +0.25)

![image](https://user-images.githubusercontent.com/250644/93955813-76eb0900-fd05-11ea-99e7-863ab7e8e801.png)

Comparing it to the one with Lightkurve1: the phase is what one typically expects.

![image](https://user-images.githubusercontent.com/250644/93955855-9124e700-fd05-11ea-9e90-37388b64a516.png)

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): `master` v2.0b1 based
-  installation method (e.g. pip, conda, source): source

**Comment by orionlee** [comment]
Diagnosis: The phase of folded lightcurve is not normalized, and is still in the scale of days.

E.g., if I change the period to 3 days, the phase will appear to be -1.5 to + 1.5

![image](https://user-images.githubusercontent.com/250644/93956676-984cf480-fd07-11ea-88bc-e70e703773ef.png)

**Comment by barentsen** [comment]
Good catch!

Returning phase in units of days is an intentional change in Lightkurve v2.x.

With this change, the `LightCurve.fold()` method now matches the exact behavior and arguments of the `TimeSeries.fold()` parent method.

There are only three minor differences between `LightCurve.fold()` and `TimeSeries.fold()`:
1. We allow the arguments to be unitless, e.g. `period=50` will be interpreted as `period=50*u.days` by default, to be more fluent and user-friendly.
2. The period/epoch/wrap parameters are recorded in `lc.meta` of the object returned.
3. We return a `FoldedLightCurve` instead of a `LightCurve` object, which adds a few convenience methods specific to a folded light curve (namely, the `plot_river` method and the `phase`, `odd_mask`, and `even_mask` properties).

I would eventually like to open a PR in `astropy` to add features 1 & 2 directly to `TimeSeries.fold()`.

To obtain the old behavior, you can pass the `normalize_phase=True` argument, which normalizes the phase into a unitless number between -0.5 and 0.5 as before.

I think the new default behavior is better because it is more informative to see the phase in units of days or hours than it is to see it in unitless units.  My impression is that showing the phase in units of hours/days is more common in the scientific literature, but I may be wrong!

(Yep, this will definitely have to be part of the "What's new in Lightkurve v2.0" guide.)

**Comment by orionlee** [comment]
That make sense. I suppose then for `interact_bls()`, it should also display folded lightcurve with units as well. 

![image](https://user-images.githubusercontent.com/250644/93971138-5b432b00-fd24-11ea-8df7-d11f43cdbc60.png)

**Comment by barentsen** [comment]
Only if it's an easy change in interact_bls!  Not the end of the world if the interactive room used normalized phase by default.

**Comment by dhomeier** [comment]
> I think the new default behavior is better because it is more informative to see the phase in units of days or hours than it is to see it in unitless units. My impression is that showing the phase in units of hours/days is more common in the scientific literature, but I may be wrong!
> 
> (Yep, this will definitely have to be part of the "What's new in Lightkurve v2.0" guide.)

Some of the old tutorials also explicitly set plotting ranges in normalised phase, so those numbers need to be updated as well.
