### ISSUE TITLE
Lightcurve plot methods: linecolor not according to style when ax is supplied

### ISSUE THREAD

**Issue by orionlee** [lightkurve/lightkurve#898]
#### Problem description

For `Lightcurve.scatter()` and other plot methods, when `ax` is supplied as an argument, the line color is not `Lightkurve`'s default black. Instead it is blue-ish color from matplotlib.

#### Example

```python
ax = plt.figure(figsize=(6, 3)).gca()
# scatter color is blue-ish (matplotlib default), rather than lightkurve's default black
lc.scatter(ax=ax) 

lc.scatter();
```

![image](https://user-images.githubusercontent.com/250644/98279221-6e196400-1f4e-11eb-9d44-f9f1faf17019.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): 1.11.3

**Comment by barentsen** [comment]
Lightkurve's default marker color is set by the `axes.prop_cycle` parameter in `lightkurve/data/lightkurve.mplstyle`:
```
axes.prop_cycle : cycler('color', ['333333', '0072B2', '009E73', 'D55E00', 'CC79A7', 'F0E442', '56B4E9'])
```
I guess that this parameter is applied when an axes object is created.  Likewise, the first plot (with the blue data points) also shows a different style for the xtick and ytick markers, suggesting that the `xtick.*` and `ytick.*` parameters in our style file are also ignored.

I'm hesitant to treat this as a bug, because aggressively enforcing our own defaults will likely make it harder for users to customize plots.

A current workaround is for the user to specify that they want to use Lightkurve's defaults, as follows:
```python
with plt.style.context(lk.MPLSTYLE):
  ax = plt.figure(figsize=(6, 3)).gca()
  lc.scatter(ax=ax)
```

I wonder if that's sufficient?

**Comment by orionlee** [comment]
I don't know about matplotlib's style enough to make any specific suggestion.

If we adopt the approaching of allowing users to use `lk.MPLSTYLE`, it needs to be documented then.

As an user, I feel using `lk.MPLSTYLE` is a bit clunky when I simply want to change the size. For my own use cases, I am not that particular about styles so I simply ignore the difference, but I suspect it might matter to some users / use cases.

One proposal:
1. Document `lk.MPLSTYLE` (as a last resort)
2. Give users some way to specify the size in various plot methods without using `lk.MPLSTYLE` context. Possibilities: 
   i. an optional parameter for size: `lc.scatter(figsize=(6,3))`
   ii. an optional parameter to control `figure` in general: `lc.scatter(figargs=dict(figsize=(6,3), dpi=300))`
