### ISSUE TITLE
Issue with astroseismology tutorial 

### ISSUE THREAD

**Issue by rebekah9969** [lightkurve/lightkurve#943]
I have been helping a user with an astroseismology tutorial and we have run into a problem 

```
search = lk.search_lightcurvefile('TIC 445359736', mission='tess', author="SPOC")

files = search.download_all()

lc = files.PDCSAP_FLUX.stitch()

lc = lc.remove_outliers().remove_nans()

pg = lc.to_periodogram(method='lombscargle', normalization='psd')

pg.frequency_at_max_power

snr = pg.flatten()

seis = snr.to_seismology()

numax = seis.estimate_numax()

numax
```

This should give you a value of numax:  2516.00
2516.00 𝜇Hz (method: ACF2D)

However if you alter one line of code above 
pg = lc.to_periodogram(method='lombscargle', normalization='psd', minimum_frequency=10,maximum_frequency=50)

then you get 
numax:  31.50
31.50 𝜇Hz  (method: ACF2D)

The latter is the correct value for this object. Why is the data so sensitive to min max frequency limits and is this normal?
The user states that for Kepler data this limit in frequency is not typically required. 

Any idea why the TESS data seems to be different in this way? Thank you

The plots below show the periodagrams in the two cases - the one which is all clustered on one end represents the pg when no frequency range is specified.
<img width="997" alt="Screen Shot 2021-02-10 at 12 07 52 PM" src="https://user-images.githubusercontent.com/17503131/107545375-36e3d000-6b99-11eb-9103-80dad68510d1.png">
<img width="1022" alt="Screen Shot 2021-02-10 at 12 13 05 PM" src="https://user-images.githubusercontent.com/17503131/107545476-5975e900-6b99-11eb-86ed-a3a998b9e82c.png">

**Comment by barentsen** [comment]
@ojhall94 Would you be willing to weigh in?

**Comment by ojhall94** [comment]
Hey @rebekah9969,

Great question! I should probably start by saying that Lightkurve's 2D ACF method is definitely not meant to be used blindly on all the data. In a very clear cut case with strong oscillation modes it would pick these up if you ran on the full frequency range, but in noisier periodograms (such as these TESS ones) you risk picking up random power excesses that aren't the one you're interested in (as happens when we find the 2516 muHz numax).

So to make a long story short, I think dependence on the min/max frequency is normal! The 2DACF should be a tool that helps you with your manual inspection of the data.

Even though the correct value of numax for this object is 31.50, I have a feeling that the 2DACF method returning this value here is almost a fluke. Looking at your first plot, this region of frequency space is very noisy, and not very suitable for the 2DACF method, since it only detects power excess. Im not sure about the exact conditions of this star -- I would expect powerful oscillations for a red giant, which would oscillate at this frequency -- but it seems like the TESS observations, which only span 3 months, may not have a lower enough noise floor to clearly detect asteroseismic oscillations here.

**Comment by rebekah9969** [comment]
Hi @ojhall94 

Thank you for your message, I will write something appropriate back to the user. Do you know of another tool that they might use which would be better in this instance? 
Thank you for your time.

**Comment by ojhall94** [comment]
Hey @rebekah9969,

I think that would depends on the goals of the user! Up until recently, these asteroseismic analysis codes were written individually by people. They could consider something like [PBjam](https://pbjam.readthedocs.io/en/latest/example-session.html) or [Diamonds](https://diamonds.readthedocs.io/en/latest/) perhaps, or they could take the 2DACF model and make some improvements to it themselves a la [Huber et al. (2009)](https://ui.adsabs.harvard.edu/abs/2009CoAst.160...74H/abstract) :)

**Comment by rebekah9969** [comment]
Thanks @ojhall94
I will pass this along.

**Comment by barentsen** [comment]
Thanks so much for this interesting discussion!  I'm closing this issue because it appears to be resolved, but feel free to comment below if anyone has further thoughts!
