### ISSUE TITLE
What is the un-deprecated equivalent of this search_lightcurvefile call?

### ISSUE THREAD

**Issue by pllim** [lightkurve/lightkurve#986]
#### Problem description

When upgraded from 1.x to 2.x, this gives deprecation warning:

```python
from lightkurve import search_lightcurvefile
lcf = search_lightcurvefile("Kepler-8", quarter=4, mission="Kepler").download()
```

The deprecation warning said I should use `search_lightcurve`, so I did, but

```python
from lightkurve import search_lightcurve
lcf = search_lightcurve("Kepler-8", quarter=4, mission="Kepler").download()
```

then gives this warning

```
lightkurve.utils.LightkurveWarning: Warning: 4 files available to download.
Only the first file has been downloaded. Please use `download_all()` or
specify additional criteria (e.g. quarter, campaign, or sector) to limit your search.
```

How do I use `search_lightcurve` without warning that is equivalent to what I was doing before?

**Comment by barentsen** [comment]
You successfully eliminated the deprecation warning by using `search_lightcurve` instead of `search_lightcurvefile`.  (Lightkurve v2 no longer makes a distinction between a LightCurve and a LightCurveFile, they are now one and the same.)

The other warning ("4 files available to download. Only the first file has been downloaded.") is caused by the fact that Lightkurve v2 returns all light curves available at MAST, whereas Lightkurve v1 only returned long cadence light curves created by the official pipeline.

In this specific case, the search instruction now returns the 60-second short cadence data of the target in addition to the 1800-second long cadence data:

<img width="558" alt="Screen Shot 2021-02-26 at 2 14 30 PM" src="https://user-images.githubusercontent.com/817669/109361014-0b214500-783d-11eb-9df5-dfaaebb444de.png">

To return to the Lightkurve v1 behavior, you now have to explicitly filter the search using `exptime=1800`, i.e.
```python
lcf = search_lightcurve("Kepler-8", quarter=4, mission="Kepler", exptime=1800).download()
```

Does this help?  Apologies for all the major changes!  Do open new issues as they emerge, these issues will no doubt be helpful for other users as well.

**Comment by pllim** [comment]
Yes, thanks!
